spring:
  application:
    name: core.ol
  web:
    error:
      include-message: always

server.port: 7002

logging:
  level:
    root: INFO
    com.github.valiclud: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
